import Job from "./Job";
import JobList from "./getjob";

export const metadata = {
  title: "Latest Job notifications ",
  description: "Generated by prem prakash ",
};


async function getJob(){
  const response = await fetch ('http://localhost:9090/job',
  {
    next: {
        revalidate: 30,
          }
  })
  return response.json()
}



export default async function Jobs() {
  // Fetch job data
  const jobsData = await getJob();
  const jobs = jobsData.content || [];

  // Function to format the date
  const formatDate = (dateString) => {
    const date = new Date(dateString);
    return date.toDateString();
  };

  return (

    <>
        {/* <div className="container mx-auto mt-8 px-10">
    <h1 className="text-2xl font-bold mb-4 text-center">Notifications</h1>
      {jobs.map((job) => (
        // <Job
        //   key={job.id}
        //   id={job.id}
        //   title={job.title}
        //   date={formatDate(job.postedDate)} // Format the posted date
        // />
        <Job key={job.id} jobdata={job} />
      ))}
    </div> */}
    
    
    <div className="container mx-auto mt-8 px-10">
    <h1 className="text-2xl font-bold mb-4 text-center">Notifications</h1>
    <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
      {jobs.map((job) => (
                <Job key={job.id} jobdata={job} />

      ))}
    </div>
  </div>
    </>


    
  );
}
