import Link from "next/link";
import Job from "./Job";

export const metadata = {
  title: "Latest Job notifications ",
  description: "Generated by prem prakash ",
};

async function getJob() {
  const response = await fetch('http://localhost:9090/job',
    {
      next: {
        revalidate: 30,
      }
    })
  return response.json()
}


export default async function Jobs() {
  // Fetch job data
  const jobsData = await getJob();
  const jobs = jobsData.content || [];

  // Function to format the date
  const formatDate = (dateString) => {
    const date = new Date(dateString);
    return date.toDateString();
  };

  return (

    <>
<div className="grid grid-cols-1 md:grid-cols-4 gap-4">
  {/* First Section */}
  <section className="md:col-span-1 hidden sm:block md:block  p-3 pl-5 ml-5">
  <h1 className="text-2xl font-bold mb-4 text-center pt-5">Latest Job List</h1>
  {jobs.map((job) => (
    <div className="p-2" key={job.id}>
      <Link href={`/jobs/${job.id}`}>
        <div className="">
          <span className="font-bold">{job.title}</span>
        </div>
        <div className="text-gray-400">
          <span>{job.description}</span>
        </div>
      </Link>
    </div>
  ))}
</section>


  {/* Second Section */}
  <section className="md:col-span-3 col-span-1">
  <div className="container mx-auto mt-8 px-10">
        <h1 className="text-2xl mb-4  text-gray-200 font-bold text-center pb-2">Latest Jobs notifications</h1>
        <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
          {jobs.map((job) => (
            <Job key={job.id} jobdata={job} />
          ))}
        </div>
      </div>
  </section>
</div>

    </>



  );
}
